{
	"version": 1559559988,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/naveboa-sheet0.png",
		"images/naveboa-sheet1.png",
		"images/btatirar-sheet0.png",
		"images/bala-sheet0.png",
		"images/baixo-sheet0.png",
		"images/esquerda-sheet0.png",
		"images/direita-sheet0.png",
		"images/fundo-sheet0.png",
		"images/naveinimiga-sheet0.png",
		"images/botondstroy-sheet0.png",
		"images/ptvida-sheet0.png",
		"images/vida-sheet0.png",
		"images/pp-sheet0.png",
		"images/explod-sheet0.png",
		"images/explod-sheet1.png",
		"images/explod-sheet2.png",
		"images/sprite-sheet0.png",
		"images/smallexplosion-sheet0.png",
		"images/smallexplosion-sheet1.png",
		"images/karlo-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/telapaly-sheet0.png",
		"images/play-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/chief_1.ogg",
		"media/laser.m4a",
		"media/laser.ogg",
		"media/laser2.m4a",
		"media/laser2.ogg",
		"media/opening menu.m4a",
		"media/opening menu.ogg",
		"media/shoot.ogg",
		"media/alarm alert ringer ascend 01.ogg"
	]
}